spring:
  #配置数据源信息
  datasource:
#    配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #链接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url与驱动类版本无关，但却和当前使用的MySQL版本有关系
    #如果是MySQL1.5版本的，则用下面的方法写
    #url: jdbc://localhost:3306//mp?characterEncoding=utf-8&&useSSL=false
    #MySQL1.8的配置如下。其中GMT%2B8是中国的时区
    url: jdbc://localhost:3306//mp?serTimezone=GMT%2B8&characterEncoding=utf-8&&useSSL=false
    username: root
    password: 123456